"""
Interactive Map Post-Processing Service.

Takes a PPTX generated by Gamma and makes existing elements clickable:
1. Makes chapter cards on the index slide clickable (link to chapter slides)
2. Makes "← Indice" buttons on other slides clickable (link back to index)
"""
import os
import json
import re
from io import BytesIO
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.oxml.ns import qn
from lxml import etree
import httpx

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')


def extract_presentation_structure(pptx_bytes: bytes) -> dict:
    """Extract detailed structure from PPTX."""
    prs = Presentation(BytesIO(pptx_bytes))
    
    slides_info = []
    for idx, slide in enumerate(prs.slides):
        shapes_info = []
        slide_title = ''
        
        for shape_idx, shape in enumerate(slide.shapes):
            if shape.has_text_frame:
                text = shape.text_frame.text.strip()
                if text:
                    shapes_info.append({
                        'idx': shape_idx,
                        'text': text[:100],
                    })
                    if not slide_title and len(text) < 80:
                        slide_title = text
        
        slides_info.append({
            'index': idx,
            'title': slide_title,
            'shapes': shapes_info,
        })
    
    return {'total_slides': len(prs.slides), 'slides': slides_info}


async def analyze_with_ai(structure: dict, source_content: str) -> dict:
    """Use AI to identify index slide and chapter mappings."""
    
    slides_summary = []
    for s in structure['slides']:
        texts = [sh['text'][:40] for sh in s['shapes'][:5]]
        slides_summary.append(f"Slide {s['index']}: {texts}")
    
    prompt = f"""Analyze this presentation structure.

SLIDES:
{chr(10).join(slides_summary)}

Find:
1. Which slide is the INDEX (table of contents with chapter list)
2. For each chapter card on the index, which slide it should link to

Return JSON:
{{
  "index_slide": <number>,
  "chapters": [
    {{"card_text": "exact text on card", "target_slide": <number>}},
    ...
  ]
}}

Rules:
- card_text must match text found on the index slide
- target_slide is where that chapter starts
- Only include clear chapter links

JSON only:"""

    if not OPENAI_API_KEY:
        return _fallback(structure)
    
    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(
                'https://api.openai.com/v1/chat/completions',
                headers={'Authorization': f'Bearer {OPENAI_API_KEY}', 'Content-Type': 'application/json'},
                json={'model': 'gpt-4o-mini', 'messages': [{'role': 'user', 'content': prompt}], 'temperature': 0.1}
            )
            
            if resp.status_code != 200:
                return _fallback(structure)
            
            content = resp.json()['choices'][0]['message']['content'].strip()
            if '```' in content:
                match = re.search(r'\{.*\}', content, re.DOTALL)
                content = match.group(0) if match else '{}'
            
            result = json.loads(content)
            print(f"[MAP] AI: index={result.get('index_slide')}, chapters={len(result.get('chapters', []))}")
            return result
    except Exception as e:
        print(f"[MAP] AI error: {e}")
        return _fallback(structure)


def _fallback(structure: dict) -> dict:
    chapters = []
    for s in structure['slides'][2:8]:
        if s['title']:
            chapters.append({'card_text': s['title'], 'target_slide': s['index']})
    return {'index_slide': 1, 'chapters': chapters}


def add_text_hyperlink(shape, target_slide, prs) -> bool:
    """
    Add hyperlink to the TEXT inside a shape.
    This is the most reliable method for PowerPoint.
    """
    try:
        rId = shape.part.relate_to(
            target_slide.part,
            'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide'
        )
        
        if shape.has_text_frame:
            for para in shape.text_frame.paragraphs:
                for run in para.runs:
                    r_elem = run._r
                    
                    rPr = r_elem.find(qn('a:rPr'))
                    if rPr is None:
                        rPr = etree.SubElement(r_elem, qn('a:rPr'))
                        r_elem.insert(0, rPr)
                    
                    for old in rPr.findall(qn('a:hlinkClick')):
                        rPr.remove(old)
                    
                    hlink = etree.SubElement(rPr, qn('a:hlinkClick'))
                    hlink.set(qn('r:id'), rId)
                    hlink.set('action', 'ppaction://hlinksldjump')
                    
            print(f"[MAP]   -> Text hyperlink added (rId={rId})")
            return True
                    
    except Exception as e:
        print(f"[MAP] Error: {e}")
    
    return False


def add_shape_hyperlink(shape, target_slide, prs) -> bool:
    """
    Add hyperlink to the SHAPE itself (entire shape clickable).
    """
    try:
        rId = shape.part.relate_to(
            target_slide.part,
            'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide'
        )
        
        sp_elem = shape._element
        
        for tag in ['p:nvSpPr', 'p:nvPicPr', 'p:nvCxnSpPr']:
            nvPr = sp_elem.find(qn(tag))
            if nvPr is not None:
                cNvPr = nvPr.find(qn('p:cNvPr'))
                if cNvPr is not None:
                    for old in cNvPr.findall(qn('a:hlinkClick')):
                        cNvPr.remove(old)
                    
                    hlink = etree.SubElement(cNvPr, qn('a:hlinkClick'))
                    hlink.set(qn('r:id'), rId)
                    hlink.set('action', 'ppaction://hlinksldjump')
                    
                    print(f"[MAP]   -> Shape hyperlink added (rId={rId})")
                    return True
                    
    except Exception as e:
        print(f"[MAP] Shape link error: {e}")
    
    return False


def find_shape_by_text(slide, text_to_find: str):
    """Find shape containing the text."""
    text_lower = text_to_find.lower().strip()
    
    for shape in slide.shapes:
        if shape.has_text_frame:
            shape_text = shape.text_frame.text.strip().lower()
            if text_lower in shape_text or shape_text in text_lower:
                return shape
    return None


def find_back_button(slide):
    """Find back-to-index button."""
    for shape in slide.shapes:
        if shape.has_text_frame:
            text = shape.text_frame.text.strip().lower()
            if 'indice' in text or '←' in text or 'torna' in text:
                return shape
    return None


def create_back_button(slide, prs):
    """Create a small back button if Gamma didn't create one."""
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    
    left = prs.slide_width - Inches(1.0)
    top = prs.slide_height - Inches(0.4)
    width = Inches(0.85)
    height = Inches(0.3)
    
    shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height)
    
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(0x66, 0x66, 0x66)
    shape.line.fill.background()
    
    tf = shape.text_frame
    tf.word_wrap = False
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = "← Indice"
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
    p.alignment = PP_ALIGN.CENTER
    
    return shape


def make_elements_clickable(pptx_bytes: bytes, nav_data: dict) -> bytes:
    """Add hyperlinks to existing elements."""
    prs = Presentation(BytesIO(pptx_bytes))
    
    index_slide_idx = nav_data.get('index_slide', 1)
    chapters = nav_data.get('chapters', [])
    
    print(f"[MAP] Index slide: {index_slide_idx}, Chapters: {len(chapters)}")
    
    if index_slide_idx < len(prs.slides):
        index_slide = prs.slides[index_slide_idx]
        
        for ch in chapters:
            card_text = ch.get('card_text', '')
            target_idx = ch.get('target_slide', 0)
            
            if not card_text or target_idx >= len(prs.slides):
                continue
            
            shape = find_shape_by_text(index_slide, card_text)
            if shape:
                target_slide = prs.slides[target_idx]
                
                success = add_shape_hyperlink(shape, target_slide, prs)
                
                if shape.has_text_frame:
                    add_text_hyperlink(shape, target_slide, prs)
                
                print(f"[MAP] Linked '{card_text[:25]}' -> slide {target_idx}")
            else:
                print(f"[MAP] Card not found: '{card_text[:25]}'")
    
    if index_slide_idx < len(prs.slides):
        index_slide = prs.slides[index_slide_idx]
        
        for slide_idx, slide in enumerate(prs.slides):
            if slide_idx == index_slide_idx:
                continue
            
            back_btn = find_back_button(slide)
            if back_btn:
                add_shape_hyperlink(back_btn, index_slide, prs)
                
                if back_btn.has_text_frame:
                    add_text_hyperlink(back_btn, index_slide, prs)
                
                print(f"[MAP] Linked back button on slide {slide_idx}")
            else:
                back_btn = create_back_button(slide, prs)
                if back_btn:
                    add_shape_hyperlink(back_btn, index_slide, prs)
                    add_text_hyperlink(back_btn, index_slide, prs)
                    print(f"[MAP] Created & linked back button on slide {slide_idx}")
    
    output = BytesIO()
    prs.save(output)
    output.seek(0)
    return output.read()


async def create_interactive_map_pptx(pptx_bytes: bytes, source_content: str) -> bytes:
    """Main function."""
    print("[MAP] Extracting structure...")
    structure = extract_presentation_structure(pptx_bytes)
    print(f"[MAP] Found {structure['total_slides']} slides")
    
    for s in structure['slides'][:5]:
        texts = [sh['text'][:30] for sh in s['shapes'][:4]]
        print(f"[MAP]   Slide {s['index']}: {texts}")
    
    print("[MAP] Analyzing with AI...")
    nav_data = await analyze_with_ai(structure, source_content)
    
    print("[MAP] Making elements clickable...")
    result = make_elements_clickable(pptx_bytes, nav_data)
    
    print("[MAP] Done!")
    return result
